routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/','IndexController',[
                                    'only'=>['index'],
                                    'names'=>['index'=>'home']
    ]);

Route::resource('/portfolios','PortfolioController',[
                                 'parameters' => [
                                     'portfolios'=>'alias'
                                 ]
]);
Route::resource('/articles','ArticlesController',[
                                          'parameters' => [
                                              'articles'=>'alias',
                                          ]
]);
Route::get('/articles/cat/{cat_alias?}',['uses'=>'ArticlesController@index','as'=>'articlesCat']);
Route::resource('comment','CommentController',['only'=>'store']);
Route::match(['get','post'],'/contacts',['uses'=>'ContactsController@index','as'=>'contacts']);

//Auth routes custom

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');
Route::get('/logout','Auth\LoginController@logout');

// /admin
Route::group(['prefix'=>config('SettingsCustom.admin_prefix'),'middleware'=>'auth'],function (){
     // /admin/
    Route::get('/',['uses'=>'Admin\IndexController@index','as'=>'adminIndex']);
    Route::resource('/aarticles','Admin\ArticlesController');
    Route::resource('/permissions','Admin\PermissionsController');
    Route::resource('/menus','Admin\MenusController');
    Route::resource('/users','Admin\UsersController');
});

resources/views/pink/admin/article_create_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group" style="width: 1200px;">
        @if(!is_array($errors))
            @if($errors->all())
                <div class="box error-box">
                    <ul style="list-style-type: none;">
                        @foreach($errors->all() as $error)
                            <li style="color: red; font-size: 14px;">{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @elseif(is_array($errors))
            <div class="box error-box">
                <ul style="list-style-type: none;">
                @foreach($errors as $error)
                    <li style="color: red; font-size: 14px;">{{$error}}</li>
                @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('aarticles.store')}}" class="contact-form" method="POST" enctype="multipart/form-data">
            <ul>
                {{csrf_field()}}
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Ady:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="title" value="{{old('title')}}" placeholder="Adyny yazyn...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Achar sozi(SEO uchin):</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="keywords" value="{{old('keywords')}}" placeholder="SEO achar sozleri..." />
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Meta opisaniya(SEO):</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="meta_desc" value="{{old('meta_desc')}}" placeholder="Meta mazmuny...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Psevdonim(Alias):</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="alias" value="{{old('alias')}}" placeholder="Alias...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Kichi mazmuny:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <textarea name="description" id="editor1" cols="30" rows="10">{{(old('description') ?? '')}}</textarea>
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Doly text:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <textarea name="full_text" id="editor2" cols="30" rows="10">{{(old('full_text') ?? '')}}</textarea>
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Suraty:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn suraty</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="file" name="image" class="filestyle" data-dragdrop="false">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Kategoriyasy:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn suraty</span><br>
                    </label>
                    <div class="input-prepend">

                        <select name="category_id" id="">
                        @if($categories)
                            @foreach($categories as $k=>$category)
                                    <optgroup label="{{$k}}">
                                       @foreach($category as $k=>$cat)
                                            <option value="{{$k}}">{{$cat}}</option>
                                        @endforeach

                                    </optgroup>
                            @endforeach
                        @endif
                        </select>
                    </div>
                </li>
                <li class="submit-button">
                    <button class="btn btn-the-salmon-dance-1" name="create_button" style="padding: 10px 30px;    box-shadow: 7px 10px 11px -8px black;font-weight: bold;
    color: #fff;background-color: forestgreen;border: 1px solid forestgreen;">Goshmak</button>
                </li>
            </ul>
        </form>
        
    </div>
</div>

resources/views/pink/admin/articles_content.blade.php
@if($articles)
    <div id="content-page" class="content-group" >
        <div class="hentry group"></div>

        @if(session('status'))
            <div class="box success-box">
            {{session('status')}}
            </div>
        @endif
        {{session()->remove('status')}}
        <h2 style="text-align: center;">Sayta goshulan statyalar</h2>
        <div class="" style="float: right; margin-bottom:1em;">
            <button class="btn" style="padding: 10px 20px;">
                <a href="{{route('aarticles.create')}}" style="color: green;font-weight: bolder;">Taze goshmak+</a>
            </button>
        </div>
            <div class="short-table white">

                <table style="width:100%;" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th class="align-left">ID</th>
                            <th>Bas Sozi</th>
                            <th>Tekst</th>
                            <th>Surat</th>
                            <th>Kategoriya</th>
                            <th>Psevdonim</th>
                            <th>Hereket</th>
                        </tr>
                    </thead>
                    <tbody>
                     @foreach($articles as $article)
                         <tr>
                             <td class="align-left">{{$article->id}}</td>
                             <td class="align-left"><a href="{{route("aarticles.edit",['aarticle'=>$article->alias])}}">
                                     {!! $article->title !!}</a></td>
                             <td class="align-left">{!! substr($article->full_text,0,100) !!}</td>
                             @if(isset($article->image->mini))
                                 <td class="align-left">
                                     <img src="{{asset(env('THEME','pink').'/assets/images/articles/'.$article->image->mini)}}" alt="">
                                 </td>
                                 @else
                                 <td>
                                     <p>No image</p>
                                 </td>
                             @endif
                             <td class="align-left">{!! $article->category->title !!}</td>
                             <td class="align-left">{!! $article->alias !!}</td>
                             <td class="align-left">
                                 <form action="{{route('aarticles.destroy',['aarticle'=>$article->alias])}}"
                                 class="form-horizontal" method="POST">
                                     {{method_field('DELETE')}}
                                     {{csrf_field()}}
                                     <input type="hidden" name="alias" value="{{strip_tags($article->alias)}}">
                                     <button class="btn btn-hem-5" style="background-color:#d86e4d;color:#fff;border:1px solid #d86e4d;" type="submit">Yok etmek</button>
                                 </form>
                             </td>
                         </tr>
                     @endforeach
                    </tbody>
                </table>
            </div>
    </div>

@else
  <div style="text-align:center;">
      <p>Artikller tapylmady</p>
  </div>
@endif

resources/views/pink/admin/custom-menu-items.blade.php
@if($items)
   @foreach($items as $item)
       <tr>
           <td style="text-align:left">{{$paddingLeft}} <a href="{{route('menus.edit',array('menu'=>$item->id))}}">{{$item->title}}</a></td>
           <td>{{ $item->url() }}</td>

           <td>
             <form action="{{route('menus.destroy',array('menu'=>$item->id))}}" method="POST">
                 {{csrf_field()}}
                 {{method_field('DELETE')}}
                 <button class="btn btn-french-5" type="submit" style="color:red;">Udalit</button>
             </form>
         </td>
     </tr>
       @if($item->hasChildren())
           @include(env('THEME','pink'.'.admin.custom-menu-items'),array('items'=>$item->children(),'paddingLeft'=>$paddingLeft.'--'));
       @endif
   @endforeach
@endif

resources/views/pink/admin/menu_create_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group" style="width: 1200px;">
        @if(!is_array($errors))
            @if($errors->all())
                <div class="box error-box">
                    <ul style="list-style-type: none;">
                        @foreach($errors->all() as $error)
                            <li style="color: red; font-size: 14px;">{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        @elseif(is_array($errors))

            <div class="box error-box">
                <ul style="list-style-type: none;">
                    @foreach($errors as $error)
                        <li style="color: red; font-size: 14px;">{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{route('menus.store')}}" class="contact-form" method="POST">
            <ul>
                {{csrf_field()}}
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Ady:</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="title" value="{{old('title')}}" placeholder="Adyny yazyn...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>URL-i</b></span>
                        <br/>
                        <span class="sublabel">Materiyalyn url-i</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="url_link" value="" placeholder="url..." />
                    </div>
                </li>
                <li class="submit-button">
                    <button class="btn btn-the-salmon-dance-1" name="create_button" style="padding: 10px 30px;    box-shadow: 7px 10px 11px -8px black;font-weight: bold;
    color: #fff;background-color: forestgreen;border: 1px solid forestgreen;">Goshmak+</button>
                </li>
            </ul>
        </form>
    </div>
</div>

resources/views/pink/admin/menus_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group">
        <h3 class="title_page">Menular</h3>

        @if(session('status'))
            <div class="success-box" style="width: 1200px;">
                <ul>
                    <li style="padding: 10px 10px 10px 50px;">{{session()->remove('status')}}</li>
                </ul>
            </div>
        @endif
        <div class="short-table white">
           <table style="width: 1200px;" cellpadding="0" cellspacing="0">
               <thead>
                  <th>Name</th>
                  <th>Link</th>
                  <th>Yok etmek</th>
               </thead>
               @if($menus)
                  @include(env('THEME','pink').'.admin.custom-menu-items',array('items'=>$menus->roots(),'paddingLeft'=>''))
               @endif
           </table>
        </div>
        <a  href="{{route('menus.create')}}" class="btn btn-the-salmon-dance-1" style="color:green;">Taze goshmak+</a>
    </div>
</div>

resources/views/pink/admin/permission_content.blade.php
<div class="content group">
    <div class="hentry group">
        <h3 class="title_page">Priveligi</h3>

        @if(session('status'))
            <div class="success-box" style="padding: 10px 0px; width: 1200px;">
                <ul>
                    <li style="margin-left: 50px;">
                        {{session('status')}}
                    </li>
                </ul>
            </div>
        @endif
        {{session_reset()}}

        <form action="{{route('permissions.store')}}" method="POST">
            {{ csrf_field() }}
            <div class="short-table white">
                 <table style="width:1200px;">
                     <th>Priveligiya</th>
                     @if(!$roles->isEmpty())
                         @foreach($roles as $item)
                             <th>{{$item->name}}</th>
                         @endforeach
                     @endif
                     <tbody>
                        @if(!$permissions->isEmpty())
                          @foreach($permissions as $per)
                              <tr>
                                  <td>{{$per->name}}</td>
                                  @foreach($roles as $role)
                                      <td>
                                          @if($role->hasPermission($per->name))
                                              <input type="checkbox" name="{{$role->id}}[]" value="{{$per->id}}" checked="checked"/>
                                              @else
                                              <input type="checkbox" name="{{$role->id}}[]" value="{{$per->id}}"/>
                                          @endif
                                      </td>
                                  @endforeach
                              </tr>
                          @endforeach
                        @endif
                     </tbody>
                 </table>
            </div>
            <input class="btn btn-unplugged-5" type="submit" value="Uytgetmek" name="re_priv_button"/>
        </form>
    </div>
</div>

resources/views/pink/admin/update_menu_content.blade.php
@if($menu)
    <div id="content-page" class="content group">
        <div class="hentry group" style="width: 1200px;">
            @if(!is_array($errors))
                @if($errors->all())
                    <div class="box error-box">
                        <ul style="list-style-type: none;">
                            @foreach($errors->all() as $error)
                                <li style="color: red; font-size: 14px;">{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            @elseif(is_array($errors))

                <div class="box error-box">
                    <ul style="list-style-type: none;">
                        @foreach($errors as $error)
                            <li style="color: red; font-size: 14px;">{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{route('menus.update',['menu'=>$menu->id])}}" class="contact-form" method="POST">
                <ul>
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                    <li class="text-field">
                        <label for="name-contact-us">
                            <span class="label"><b>Ady:</b></span>
                            <br/>
                            <span class="sublabel">Materiyalyn ady</span><br>
                        </label>
                        <div class="input-prepend">
                            <input type="text" name="title" value="{{$menu->title}}" placeholder="Adyny yazyn...">
                        </div>
                    </li>
                    <li class="text-field">
                        <label for="name-contact-us">
                            <span class="label"><b>URL-i</b></span>
                            <br/>
                            <span class="sublabel">Materiyalyn url-i</span><br>
                        </label>
                        <div class="input-prepend">
                            <input type="text" name="url_link" value="{{$menu->url_link}}" placeholder="url..." />
                        </div>
                    </li>
                    <li class="submit-button">
                        <button class="btn btn-the-salmon-dance-4" name="update_button" style="color:green">Uytgetmek</button>
                    </li>
                </ul>
            </form>
        </div>
    </div>

@endif

resources/views/pink/admin/update_user_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group" style="width: 1200px;">
        @if(!is_array($errors))
            @if($errors->all())
                <div class="box error-box">
                    <ul style="list-style-type: none;">
                        @foreach($errors->all() as $error)
                            <li style="color: red; font-size: 14px;">{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        @elseif(is_array($errors))
            <div class="box error-box">
                <ul style="list-style-type: none;">
                    @foreach($errors as $error)
                        <li style="color: red; font-size: 14px;">{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('users.update',['user'=>$user->id])}}" class="contact-form" method="POST" enctype="multipart/form-data">
            <ul>
                {{csrf_field()}}
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Ady:</b></span>
                        <br/>
                        <span class="sublabel">User ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="name" value="{{$user->name}}" placeholder="Adyny yazyn...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Login:</b></span>
                        <br/>
                        <span class="sublabel">User login</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="login" value="{{$user->login}}" placeholder="Login..." />
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>E-mail:</b></span>
                        <br/>
                        <span class="sublabel">Email</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="email" placeholder="Email..." value="{{$user->email}}">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Parol:</b></span>
                        <br/>
                        <span class="sublabel">Parol</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="password" name="password" placeholder="password...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Password Confirm:</b></span>
                        <br/>
                        <span class="sublabel">Confirm password</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="password" name="password_confirmation" placeholder="Cofirm password">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Roly:</b></span>
                        <br/>
                        <span class="sublabel">Roly saylan</span><br>
                    </label>
                    <div class="input-prepend">
                        <select name="role_id" id="">
                            @if($roles)
                                @foreach($roles as $k=>$role)
                                    <option value="{{$k+1}}"  @if($user->roles()->first()->id == $k+1) selected @endif >{{$role->name}}</option>
                                @endforeach
                            @endif
                        </select>
                    </div>
                </li>
                @if(isset($user->id))
                    <input type="hidden" name="_method" value="PUT">
                @endif

                <li class="submit-button">
                    <button class="btn btn-the-salmon-dance-1" name="update_button" style="color: green; font-weight: bold;">Uytgetmek</button>
                </li>
            </ul>
        </form>

    </div>
</div>

resources/views/pink/admin/user_create.blade.php
<div id="content-page" class="content group">
    <div class="hentry group" style="width: 1200px;">
        @if(!is_array($errors))
            @if($errors->all())
                <div class="box error-box">
                    <ul style="list-style-type: none;">
                        @foreach($errors->all() as $error)
                            <li style="color: red; font-size: 14px;">{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        @elseif(is_array($errors))
            <div class="box error-box">
                <ul style="list-style-type: none;">
                    @foreach($errors as $error)
                        <li style="color: red; font-size: 14px;">{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('users.store')}}" class="contact-form" method="POST" enctype="multipart/form-data">
            <ul>
                {{csrf_field()}}
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Ady:</b></span>
                        <br/>
                        <span class="sublabel">User ady</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="name" value="{{old('name')}}" placeholder="Adyny yazyn...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Login:</b></span>
                        <br/>
                        <span class="sublabel">User login</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="login" value="{{old('login')}}" placeholder="Login..." />
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>E-mail:</b></span>
                        <br/>
                        <span class="sublabel">Email</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="text" name="email" placeholder="Email...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Parol:</b></span>
                        <br/>
                        <span class="sublabel">Parol</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="password" name="password" placeholder="password...">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Password Confirm:</b></span>
                        <br/>
                        <span class="sublabel">Confirm password</span><br>
                    </label>
                    <div class="input-prepend">
                        <input type="password" name="password_confirmation" placeholder="Cofirm password">
                    </div>
                </li>
                <li class="text-field">
                    <label for="name-contact-us">
                        <span class="label"><b>Roly:</b></span>
                        <br/>
                        <span class="sublabel">Roly saylan</span><br>
                    </label>
                    <div class="input-prepend">
                        <select name="role_id" id="">
                        @if($roles)
                            @foreach($roles as $k=>$role)
                                    <option value="{{$k+1}}">{{$role->name}}</option>
                            @endforeach
                        @endif
                        </select>
                    </div>
                </li>
                <li class="submit-button">
                    <button class="btn btn-the-salmon-dance-1" name="create_button" style="color: green; font-weight: bold;">Goshmak</button>
                </li>
            </ul>
        </form>

    </div>
</div>

resources/views/pink/admin/users_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group">
       <h3 class="title_page">Userler</h3>
        @if(session('status'))
            <div class="box success-box" style="width: 1100px;">
                {{session('status')}}
            </div>
        @endif
        {{session()->remove('status')}}
        <div class="short-table white">
            <table style="width: 1200px;" cellspacing="0" cellpadding="0">
                <thead>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Login</th>
                <th>Role</th>
                <th>Yok Etmek</th>
                </thead>
                @if($users)
                     @foreach($users as $user)
                         <tr>
                             <td style="font-size: 16px !important;">{{$user->id}}</td>
                             <td><a style="font-size: 16px !important;" href="{{route('users.edit',['user'=>$user->id])}}">{{$user->name}}</a></td>
                             <td style="font-size: 16px !important;">{{$user->email}}</td>
                             <td style="font-size: 16px !important;">{{$user->login}}</td>
                             <td style="font-size: 16px !important;">{{$user->roles->implode('name',', ')}}</td>
                             <td style="font-size: 16px !important;">
                                 <form action="{{route('users.destroy',['user'=>$user->id])}}" method="POST">
                                     {{method_field('DELETE')}}
                                     {{csrf_field()}}
                                     <button type="submit" name="del_button" class="btn btn-the-salmon-dance-1" style="color:red; font-weight: bolder;">Delete</button>
                                 </form>
                             </td>
                         </tr>
                     @endforeach
                @endif
            </table>
        </div>
        <a class="btn btn-the-salmon-dance-1" style="color: green; font-weight: bold;" href="{{route('users.create')}}">Taze gohsmak+ </a>
    </div>
</div>