routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/','IndexController',[
                                    'only'=>['index'],
                                    'names'=>['index'=>'home']
    ]);

Route::resource('/portfolios','PortfolioController',[
                                 'parameters' => [
                                     'portfolios'=>'alias'
                                 ]
]);
Route::resource('/articles','ArticlesController',[
                                          'parameters' => [
                                              'articles'=>'alias',
                                          ]
]);
Route::get('/articles/cat/{cat_alias?}',['uses'=>'ArticlesController@index','as'=>'articlesCat']);
Route::resource('comment','CommentController',['only'=>'store']);
Route::match(['get','post'],'/contacts',['uses'=>'ContactsController@index','as'=>'contacts']);

//Auth routes custom

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');
Route::get('/logout','Auth\LoginController@logout');

// /admin
Route::group(['prefix'=>config('SettingsCustom.admin_prefix'),'middleware'=>'auth'],function (){
     // /admin/
    Route::get('/',['uses'=>'Admin\IndexController@index','as'=>'adminIndex']);
    Route::resource('/aarticles','Admin\ArticlesController');
    Route::resource('/permissions','Admin\PermissionsController');
    Route::resource('/menus','Admin\MenusController');
    Route::resource('/users','Admin\UsersController');
});

resources/views/pink/article_on_details.blade.php
<div id="content-single" class="content group">
    <div class="hentry hentry-post blog-big group ">
        <!-- post featured & title -->
        @if($article)
            <div class="thumbnail">
                <!-- post title -->
                <h1 class="post-title"><a href="#">{!! $article->title !!}</a></h1>
                <!-- post featured -->
                <div class="image-wrap">
                    <img src="{{asset(env('THEME','pink'))}}/assets/images/articles/{{$article->image->max}}" alt="{{$article->title}}" title="{{$article->title}}" />
                </div>
                <p class="date">
                    <span class="month">{{$article->created_at->format('M')}}</span>
                    <span class="day">{{$article->created_at->format('d')}}</span>
                </p>
            </div>
            <!-- post meta -->
            <div class="meta group">
                <p class="author"><span>by <a href="#" title="Posts by {{$article->user->name}}" rel="author">{{$article->user->name}}</a></span></p>
                <p class="categories"><span>In: <a href="{{route('articlesCat',['cat_alias'=>$article->category->alias])}}" title="View all posts in {{$article->category->title}}" rel="category tag">{{$article->category->title}}</a></span></p>
                <p class="comments"><span><a href="#comments" title="Comment on {{$article->title}}">{{count($article->comment)}} {{Lang::choice('ru.comments',count($article->comment))}}</a></span></p>
            </div>
            <!-- post content -->
            <div class="the-content single ">
                {!! $article->full_text!!}
                <div class="socials">
                    <h2>love it, share it!</h2>
                    <a href="https://www.facebook.com/sharer.html?u=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;t=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small facebook-small" title="Facebook">facebook</a>
                    <a href="https://twitter.com/share?url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;text=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small twitter-small" title="Twitter">twitter</a>
                    <a href="https://plusone.google.cgroupom/_/+1/confirm?hl=en&amp;url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;title=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small google-small" title="Google">google</a>
                    <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;media=http://yourinspirationtheme.com/demo/pinkrio/files/2012/09/00212.jpg&amp;description=Fusce+nec+accumsan+eros.+Aenean+ac+orci+a+magna+vestibulum+posuere+quis+nec+nisi.+Maecenas+rutrum+vehicula+condimentum.+Donec+volutpat+nisl+ac+mauris+consectetur+gravida.+Lorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.+Donec+vel+vulputate+nibh.+Pellentesque%5B...%5D" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
                    <a href="http://yourinspirationtheme.com/demo/pinkrio/2012/09/24/this-is-the-title-of-the-first-article-enjoy-it/" class="socials-small bookmark-small" title="This is the title of the first article. Enjoy it.">bookmark</a>
                </div>
            </div>
            <p class="tags">Tags: <a href="#" rel="tag">book</a>, <a href="#" rel="tag">css</a>, <a href="#" rel="tag">design</a>, <a href="#" rel="tag">inspiration</a></p>
            <div class="clear"></div>
            @else
            <h2 style="color:red;text-align:center;">Article tapylmady!</h2>
        @endif
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
        <h3 id="comments-title">
            <span>{{count($article->comments)}}</span> {{Lang::choice('ru.comments',count($article->comments))}}
        </h3>
        @set ($com,$article->comments->groupBy('parent_id'))
        @if(count($article->comments) > 0)

        @endif

        <ol class="commentlist group">
            @foreach($com as $k=>$comments)
                @if($k !==0)
                    @break
                @endif
                @include(env('THEME','pink').'.comment',['items'=>$comments])
            @endforeach
        </ol>

        <!-- START TRACKBACK & PINGBACK -->
        <h2 id="trackbacks">Trackbacks and pingbacks</h2>
        <ol class="trackbacklist"></ol>
        <p><em>No trackback or pingback available for this article.</em></p>

        <!-- END TRACKBACK & PINGBACK -->
        <div id="respond">
            <div class="wrap_result bg-info" style="padding: 15px 10px;text-align: center;z-index:6000; display: none;color:green;height:auto;border:1px solid green;font-size: 16px;border-radius:5px;background-color: #fff;"></div>
            <h3 id="reply-title">Leave a <span>Reply</span> <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></small></h3>

            <form action="{{route('comment.store')}}" method="post" id="commentform">
                {{csrf_field()}}
                @if(!Auth::check())
                <p class="comment-form-author"><label for="author">Name</label> <input id="author" name="name" type="text" value="" size="30" aria-required="true" /></p>
                <p class="comment-form-email"><label for="email">Email</label> <input id="email" name="email" type="text" value="" size="30" aria-required="true" /></p>
                <p class="comment-form-url"><label for="url">Website</label><input id="url" name="site" type="text" value="" size="30" /></p>
                 @else
                    <div class="light_rounded">
                        <p>Siz kommentariyany -  <strong>{{($article->user !== 0) ? $article->user->name : 'Anonymous'}}</strong> hokmunde goshyanyz!</p>
                    </div>
                @endif

                <p class="comment-form-comment"><label for="comment">Your comment</label><textarea id="comment" name="text" cols="45" rows="8"></textarea></p>
                <div class="clear"></div>
                <p class="form-submit">
                    <input type="hidden" id="comment_post_ID" name="comment_post_ID" value="{{$article->id}}">
                    <input type="hidden" id="comment_parent" name="comment_parent" value="0">
                    <input name="submit" type="submit" id="submit" value="Post Comment" />
                </p>
            </form>

        </div>
        <!-- #respond -->
    </div>
    <!-- END COMMENTS -->
</div>

resources/views/pink/articlesBar.blade.php
<div class="widget-first widget recent-posts">
    <h3>{{Lang::get('ru.latest_projects_tm')}}</h3>
        <div class="recent-post group">
            @if($comments)
               {{--{{dd($comments)}}--}}
                @foreach($portfolios as $portfolio)
                    <div class="hentry-post group">
                        <div class="thumb-img"><img style="width: 55px;" src="{{asset(env('THEME','pink')).'/assets/images/projects/'.$portfolio->image->mini}}" alt="{{$portfolio->title}}" title="{{$portfolio->title}}" /></div>
                        <div class="text">
                            <a href="{{route('portfolios.show',['alias'=>$portfolio->alias])}}" title="{{strip_tags($portfolio->title)}}" class="title">{!! $portfolio->title !!}</a>
                            {!! substr($portfolio->text,0,100) !!}
                            <a class="read-more" href="{{route('articles.show',['alias'=>$portfolio->alias])}}">
                                &rarr; {{Lang::get('ru.read_more')}}</a>
                        </div>
                    </div>
                @endforeach
            @else
                <h4 style="color:red;text-align: center;">{{Lang::get('ru.not_found_portfolio')}}</h4>
            @endif
        </div>
    </div>

    <div class="widget-last widget recent-comments">
        <h3>{{Lang::get('ru.recent_comments_tm')}}</h3>
        <div class="recent-post recent-comments group">

            @if(!($comments->isEmpty()))
                @foreach($comments as $comment)
                    <div class="the-post group">
                        <div class="avatar">
                        <img alt="" src="{{asset(env('THEME','pink'))}}/assets/images/avatar/{{($comment->user !== null) ? $comment->user->image : 'unknow55.png'}}"
                                             class="avatar" />
                        </div>
                        <span class="author"><strong><a href="#">{{($comment->user !== null) ? $comment->user->name : $comment->name }}</a></strong> in</span>
                        <a class="title" href="{{route('articles.show',['alias'=>$comment->article->alias])}}">
                            {{$comment->article->title}}</a>
                        <p class="comment">
                            {!!substr($comment->text,0,50)!!}..
                            <a class="goto" href="{{route('articles.show',['alias'=>$comment->article->alias])}}">&#187;</a>
                        </p>
                    </div>
                @endforeach
                @else
                <h4 style="color:red;text-align: center;">{{Lang::get('ru.not_found_comments')}}</h4>
            @endif
        </div>
    </div>

resources/views/pink/comment.blade.php
@foreach($items as $item)
    <li id="li-comment-{{$item->id}}" class="comment even {{ ($item->user_id == $article->user_id) ? 'bypostauthor odd' : '' }}">
        <div class="comment-container">
            <div class="comment-author vcard">

                @set($hash,isset($item->email) ? md5($item->email) : md5($item->user->email))

                <img alt="" src="https://gravatar.com/avatar/{{$hash}}?d=mm&s=75" class="avatar" height="75" width="75" />
                <cite class="fn">{{($item->name) ? $item->name : $item->user->name }}</cite>
            </div>
            <!-- .comment-author .vcard -->
            <div class="comment-meta commentmetadata">
                <div class="intro">
                    <div class="commentDate">
                        <a href="#comment-2">
                            {{is_object($item->created_at) ? $item->created_at->format('M 3, Y \a\t h:m a') : '' }}</a>
                    </div>
                    <div class="commentNumber">#&nbsp;</div>
                </div>
                <div class="comment-body">
                    <p>{{$item->text}}</p>
                </div>
                <div class="reply group">
                    <a class="comment-reply-link" href="#respond" onclick="return addComment.moveForm(&quot;comment-{{$item->id}}&quot;, &quot;{{$item->id}}&quot;, &quot;respond&quot;, &quot;{{$item->article_id}}&quot;)">{{Lang::get('ru.reply')}}</a>
                    <div class="id_number" style="display: none;">{{$item->id}}</div>
                </div>
                <!-- .reply -->
            </div>
            <!-- .comment-meta .commentmetadata -->
        </div>
        <!-- #comment-##  -->
        @if(isset($com[$item->id]))
            <ul class="children">
                @include(env('THEME','pink').'.comment',['items'=>$com[$item->id]])
            </ul>
        @endif
    </li>
@endforeach

resources/views/pink/contacts_content.blade.php
<!-- START PAGE META -->
<div id="page-meta">
    <div class="inner group">
        <h3>{{trans('ru.contacts_text_1')}}</h3>
        <h4>{{trans('ru.contacts_text_2')}}</h4>
    </div>
</div>
<!-- END PAGE META -->
<!-- START PRIMARY -->
        <!-- START CONTENT -->
        <div id="content-page" class="content group">
            <div class="hentry group">
                @if(count($errors))
                    <div class="msg-error">
                        <ul style="color:red;">
                        @foreach($errors->all() as $error)
                            <li style="color:red;">{{ $error }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                @if(session('status'))
                        <div class="box success-box">
                            {!! session('status') !!}
                        </div>
                @endif
                <form id="contact-form-contact-us" class="contact-form"
                      method="post" action="{{route('contacts')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="usermessagea"></div>
                    <fieldset>
                        <ul>
                            <li class="text-field">
                                <label for="name-contact-us">
                                    <span class="label">Name</span>
                                    <br />					<span class="sublabel">This is the name</span><br />
                                </label>
                                <div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span>
                                    <input type="text" name="name" id="name-contact-us" class="required" value="{{old('name','')}}" />
                                </div>
                                <div class="msg-error"></div>
                            </li>
                            <li class="text-field">
                                <label for="email-contact-us">
                                    <span class="label">Email</span>
                                    <br />					<span class="sublabel">This is a field email</span><br />
                                </label>
                                <div class="input-prepend"><span class="add-on"><i class="icon-envelope"></i></span>
                                    <input type="text" name="email" id="email-contact-us" class="required email-validate" value="{{old('email')}}" />
                                </div>
                                <div class="msg-error"></div>
                            </li>
                            <li class="textarea-field">
                                <label for="message-contact-us">
                                    <span class="label">Message</span>
                                </label>
                                <div class="input-prepend"><span class="add-on"><i class="icon-pencil"></i></span>
                                    <textarea name="message" id="message-contact-us" rows="8" cols="30" class="required">{{old('message')}}</textarea>
                                </div>
                                <div class="msg-error"></div>
                            </li>
                            <li class="submit-button">
                                {{--<input type="text" name="yit_bot" id="yit_bot" />--}}
                                {{--<input type="hidden" name="yit_action" value="sendmail" id="yit_action" />--}}
                                {{--<input type="hidden" name="yit_referer" value="http://yourinspirationtheme.com/demo/pinkrio/corporate/contact/" />--}}
                                <input type="hidden" name="form_location" value="Pink rio Kontaktlar sahypasyndaky formdan gelen hat!" />
                                <input type="submit" name="yit_sendmail" value="{{trans('ru.send_mail')}}" class="sendmail alignright" />
                            </li>
                        </ul>
                    </fieldset>
                </form>
                {{--<script type="text/javascript">--}}
                    {{--var messages_form_126 = {--}}
                        {{--name: "Please, fill in your name",--}}
                        {{--email: "Please, insert a valid email address",--}}
                        {{--message: "Please, insert your message"--}}
                    {{--};--}}
                {{--</script>--}}
            </div>
            <!-- START COMMENTS -->
            <div id="comments">
            </div>
            <!-- END COMMENTS -->
        </div>
        <!-- END CONTENT -->

        <!-- START SIDEBAR -->
        <!-- END SIDEBAR -->

resources/views/pink/content.blade.php
@if($portfolios && count($portfolios)>0)
<div id="content-home" class="content group">
    <div class="hentry group">
        <div class="section portfolio">

            <h3 class="title">{{trans('ru.latest_projects')}}</h3>
            @foreach($portfolios as $k=>$item)
                @if($portfolios->first() == $item)
                    <div class="hentry work group portfolio-sticky portfolio-full-description">
                        <div class="work-thumbnail">
                            <a class="thumb"><img src="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$item->image->first}}" alt="{{$item->title}}" title="{{$item->title}}" /></a>
                            <div class="work-overlay">
                                <h3><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{{$item->title}}</a></h3>
                                <p class="work-overlay-categories"><img src="{{asset(env('THEME','pink'))}}/assets/images/categories.png" alt="Categories" /> in: <a href="">{{$item->filter->title}}</a></p>
                            </div>
                        </div>
                        <div class="work-description">
                            <h2><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{{$item->title}}</a></h2>
                            <p class="work-categories">in: <a href="#">{{$item->filter->title}}</a></p>
                            <p>{!!substr($item->text,0,250)!!}</p>
                            <a href="{{route('portfolios.show',['alias'=>$item->alias])}}" class="read-more">|| Read more</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                    @continue
                @endif
                @if($k==1)
                    <div class="portfolio-projects">
                @endif
                <div class="related_project {{($portfolios->last() == $item) ? 'related_project_last' : ''}}">
                    <div class="overlay_a related_img">
                        <div class="overlay_wrapper">
                            <img src="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$item->image->mini}}" alt="{{$item->title}}" title="{{$item->title}}" />
                            <div class="overlay">
                                <a class="overlay_img" href="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$item->image->path}}" rel="lightbox" title="{{$item->title}}"></a>
                                <a class="overlay_project" href="{{route('portfolios.show',['alias'=>$item->alias])}}"></a>
                                <span class="overlay_title">{!!$item->title!!}</span>
                            </div>
                        </div>
                    </div>
                    <h4><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{!! $item->title !!}</a></h4>
                    <p>{!! substr($item->text,0,100) !!}</p>
                </div>
                @endforeach
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
    </div>
    <!-- END COMMENTS -->
</div>
    @else
    <p>Portfolio yok!</p>
@endif

resources/views/pink/index.blade.php
@extends(env('THEME','pink').'.layouts.site-layout')
@section('header')
  {!! $header !!}
@endsection
@section('sliders')
   {!! $sliders !!}
@endsection
@section('content')
    {!! $content !!}
@endsection
@section('bar')
    {!! $rightBar !!}
@endsection
@section('footer')
   {!! $footer !!}
@endsection

resources/views/pink/indexBar.blade.php
@if($articles)
    <div class="widget-first widget recent-posts">
        <h3>{{trans('ru.from_our_blog')}}</h3>
        <div class="recent-post group">
            @foreach($articles as $article)
                <div class="hentry-post group">
                    <div class="thumb-img"><img src="{{asset(env('THEME','pink'))}}/assets/images/articles/{{$article->image->mini}}" alt="{{$article->title}}" title="{{$article->title}}" /></div>
                    <div class="text">
                        <a href="{{route('articles.show',['alias'=>$article->alias])}}" title="{{strip_tags($article->title)}}" class="title">{!! $article->title !!}</a>
                        <p class="post-date">{{$article->created_at->format('F d, Y')}}</p>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

    <div class="widget-last widget text-image">
        <h3>Customer support</h3>
        <div class="text-image" style="text-align:left"><img src="{{asset(env('TTHEME','pink'))}}/assets/images/callus.gif" alt="Customer support" /></div>
        <p>Proin porttitor dolor eu nibh lacinia at ultrices lorem venenatis. Sed volutpat scelerisque vulputate. </p>
    </div>
@else
  <p>No post</p>
@endif

resources/views/pink/portfolio_on_details.blade.php
@if($portfolio)
    <div id="content-page" class="content group">
        <div class="clear"></div>
        <div class="posts">
            <div class="group portfolio-post internal-post">
                <div id="portfolio" class="portfolio-full-description">

                    <div class="fulldescription_title gallery-filters">
                        <h1>{{$portfolio->title}}</h1>
                    </div>

                    <div class="portfolios hentry work group">
                        <div class="work-thumbnail">
                            <a class="thumb"><img src="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$portfolio->image->path}}" alt="{{strip_tags($portfolio->title)}}" title="{!! $portfolio->title !!}" /></a>
                        </div>
                        <div class="work-description">
                           <div class="t">{!! $portfolio->text !!}</div>
                            <div class="clear"></div>
                            <div class="work-skillsdate">
                                <p class="skills"><span class="label">Filters:</span> {{$portfolio->filter->title}}</p>
                                <p class="workdate"><span class="label">Customer:</span>{!! $portfolio->cutomer !!}</p>
                                @if($portfolio->created_at)
                                    <p class="workdate"><span class="label">Year:</span>{{$portfolio->created_at->format('Y')}}</p>
                                @endif
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="clear"></div>

                    <h3>{{trans('ru.other_projects')}}</h3>

                    <div class="portfolio-full-description-related-projects">
                        @if($portfolios)
                            @foreach($portfolios as $port)
                                <div class="related_project">
                                    <a class="related_proj related_img" href="{{route('portfolios.show',['alias'=>$port->alias])}}" title="{!! $port->title !!}"><img src="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$port->image->mini}}" alt="{{strip_tags($port->title)}}" title="{!! $port->title !!}" /></a>
                                    <h4><a href="{{route('portfolios.show',['alias'=>$port->alias])}}">{!! $port->title !!}</a></h4>
                                </div>
                            @endforeach
                            @else
                            <p style="text-align:center">{{trans('ru.not_other_project')}}</p>
                        @endif

                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    @else
    <p style="text-align:center">Portfolio Tapylmady</p>
@endif

resources/views/pink/portfolios.blade.php
@extends(env('THEME','pink').'.layouts.site-layout')
@section('header')
    {!! $header !!}
@endsection
@section('content')
    {!! $content !!}
@endsection
@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/portfolios_content.blade.php
<!-- START PAGE META -->
<div id="page-meta">
    <div class="inner group">
        <h3>{{trans('ru.port_text1')}}</h3>
        <h4>{{trans('ru.port_text2')}}</h4>
    </div>
</div>
<!-- END PAGE META -->
@if($portfolios)
    <div id="primary" class="sidebar-no">
        <div class="inner group">
            <!-- START CONTENT -->
            <div id="content-page" class="content group">
                <div class="hentry group">
                    {{--<script>--}}
                        {{--jQuery(document).ready(function($){--}}
                            {{--$('.sidebar').remove();--}}

                            {{--if( !$('#primary').hasClass('sidebar-no') ) {--}}
                                {{--$('#primary').removeClass().addClass('sidebar-no');--}}
                            {{--}--}}

                        {{--});--}}
                    {{--</script>--}}
                    <div id="portfolio" class="portfolio-big-image">
                        @foreach($portfolios as $portfolio)
                            <div class="hentry work group">
                                <div class="work-thumbnail">
                                    <div class="nozoom">
                                        <img src="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$portfolio->image->max}}" alt="{{$portfolio->title}}" title="{{$portfolio->title}}" />
                                        <div class="overlay">
                                            <a class="overlay_img" href="{{asset(env('THEME','pink'))}}/assets/images/projects/{{$portfolio->image->path}}" rel="lightbox" title="Love"></a>
                                            <a class="overlay_project" href="{{route('portfolios.show',['alias'=>$portfolio->alias])}}"></a>
                                            <span class="overlay_title">{!! $portfolio->title !!}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="work-description">
                                    <h3>{!! $portfolio->title !!}</h3>
                                    <div class="t">
                                        {!! substr($portfolio->text,0,250).'...' !!}
                                    </div>
                                    <div class="clear"></div>
                                    <div class="work-skillsdate">
                                        <p class="skills"><span class="label">Filters:</span>{{$portfolio->filter->title }}</p>
                                        <p class="workdate"><span class="label">Customer:</span>{{$portfolio->customer}}</p>
                                        @if($portfolio->created_at)
                                        <p class="workdate"><span class="label">Year:</span>{{$portfolio->created_at->format('Y')}}</p>
                                        @endif
                                    </div>
                                    <a class="read-more" href="{{route('portfolios.show',['alias'=>$portfolio->alias])}}">{{trans('ru.view_project')}}</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        @endforeach

                            @if($portfolios->lastPage() > 1)
                                <div class="general-pagination group">
                                    @if($portfolios->currentPage() !== 1)
                                        <a href="{{($portfolios->url($portfolios->currentPage()-1)) }}">{!!Lang::get('pagination.previous')!!}</a>
                                    @endif
                                    @for($i=1;$i<=($portfolios->lastpage());$i++)
                                        @if($i == $portfolios->currentPage())
                                            <a  class="selected disabled">{{$i}}</a>
                                        @else
                                            <a href="{{$portfolios->url($i)}}">{{$i}}</a>
                                        @endif
                                    @endfor
                                    @if($portfolios->currentPage() !== $portfolios->lastPage())
                                        <a href="{{($portfolios->url($portfolios->currentPage()+1))}}">{!! Lang::get('pagination.next') !!}</a>
                                    @endif
                                    {{--<a href="#" class="selected">1</a><a href="#">2</a><a href="#">&rsaquo;</a>--}}
                                </div>
                            @endif

                    </div>
                    <div class="clear"></div>
                </div>
                <!-- START COMMENTS -->
                <div id="comments">
                </div>
                <!-- END COMMENTS -->
            </div>
            <!-- END CONTENT -->
            <!-- START EXTRA CONTENT -->
            <!-- END EXTRA CONTENT -->
        </div>
    </div>
    @else
    <p class="" style="text-align: center;">Portfolioda Yok!</p>
@endif

resources/views/pink/rightBar.blade.php
<div class="sidebar group">
    {!! $content_rightBar !!}
</div>